name: Monorepo Coverage
description: Generate coverage badge for each project in a monorepo
author: Aaron Marais
branding:
  icon: more-horizontal
  color: gray-dark
inputs:
  GITHUB_TOKEN:
    description: The username of the user that initiated the workflow run. Required when creating the coverage branch
    required: false
  COVERAGE_BRANCH:
    description: Branch to create & store your totle coverage data in
    required: false
  ROOT:
    description: When not using autodiscovery, this is the folder which contains all your packages
    required: false
  PACKAGES:
    description: When not using autodiscovery, these are the packages to run coverage on
    required: false
  BADGE_BRANCH:
    description: Branch to push coverage badges to
    required: false
outputs:
  COVERAGE:
    description: Coverage for all packages
runs:
  using: 'node16'
  main: 'dist/index.js'
